### ISSUE TITLE
The makefile "install" goal writes config files as executables

### ISSUE THREAD

**Issue by livingsilver94** [getsolus/aa-lsm-hook#5]
To the `install` command [here](https://github.com/getsolus/aa-lsm-hook/blob/9a41585844e96d917dbc044ec4db6a292fa6897f/Makefile#L60) is passed a `00755` mode, which is correct for directory creation but not optimal for the config file and systemd service unit. A permission mode like `00644` would be ideal. In fact, systemd complains about `aa-lsm-hook.service` being executable when it reloads services.

**Comment by DataDrake** [comment]
This is now resolved.
